FROM nginx:1.19-alpine

RUN rm /etc/nginx/conf.d/default.conf
# 80 default rewrite
COPY default.conf /etc/nginx/conf.d 
# 443
COPY nginx.conf.prod /etc/nginx/conf.d/nginx.conf
COPY scarlet.pro.key /etc/nginx/cert/
COPY scarlet.pro.pem /etc/nginx/cert/
