# 非https的nginx 80 生产模拟

FROM byjg/nginx-extras

# change tsinghua mirror ?
# alpine
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
RUN apk update 

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf.dev /etc/nginx/conf.d/nginx.conf
COPY nginx_template.xslt /etc/nginx/conf.d/nginx_template.xslt
# 重启 加载模块
# RUN nginx -t && nginx -s reload